# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20161211_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='deliver_date',
            field=models.DateTimeField(blank=True, verbose_name='date delivered'),
        ),
    ]
