# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20161204_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='exchange.Profile'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='exchange.Profile'),
        ),
    ]
