# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20161204_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='category',
            field=models.ForeignKey(default='random', on_delete=django.db.models.deletion.CASCADE, to='exchange.Category'),
        ),
    ]
