# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20161212_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='deliver_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date delivered'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='giver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='exchange.Profile'),
        ),
    ]
