# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20161212_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
